# try:
#     data = [{"name": "Пётр", "phone": "123"}, {"name": "Иван"}]
#     print(data[1]["phone"])
# # except Exception:
#     print('Exception')
# except NameError:
#     print('NameError')
# except NameError:
#     print('NameError')
# except NameError:

# data = [{"name": "Пётр", "phone": "123"}, {"name": "Иван"}]
# print(data[1]["phone"])